### ISSUE TITLE
Return value corrupted by compiler

### ISSUE THREAD

**Issue by andreforme** [xboxfanj/math-neon#11]
Hello,
I tried to use the library on an ARM Cortex A9 (the specific device is Zynq, from Xilinx). I tested in particular the sinf_neon function. When I compile the entire project, the compiler add to the generated assembly code, the following instruction as last instruction of sinf_neon function

"mov r0, r3"

This causes that the R0 register, which should contain the return value, is overwritten with a wrong value.
Please note that it ONLY happen when I DO NOT activate the compiler optimization (-O0). Does anyone know why it happens?

Thanks in advance

Regards,
Andrea

**Comment by xboxfanj** [comment]
Honestly, I just grabbed this since Google Code was going down.  I'm not an Assembly expert.

Try emailing the author.  He responded to me very quickly.

**Comment by andreforme** [comment]
Unfortunately, the only solution I found is to rewrite the wrapper function grouping the instructions within a single asm block and I used operand lists as follow

float sinf_neon_sfp (float x)
{ 
  asm volatile ("vdup.f32     d0,%[r_op]      \n\t" 
                       "blx              %[r_fn]            \n\t" 
                       "vmov.f32     %[r_op],s0      \n\t" 
                       : [r_op]"+r" (x) 
                       : [r_fn]"r"  (sinf_neon_hfp) 
                       : "r14" );
  return x;
}
